### ISSUE TITLE
Micro Front Ends -- Build Legacy Agent From Modular Code

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#182]
#### Why

With as many moving parts as there will be in the process of re-architecting the agent, we need something to run sanity checks on through the entire process.  It will be important to establish this first so we can be sure we do not break existing features, and can still ship existing value.

#### Tasks

- [ ] Build script can generate the legacy code so that we have sanity checks in place while developing
- [ ] Check if methodologies covered in the legacy `prelude` files still work with the new build
- [ ] Run existing test suite on build output

**Comment by metal-messiah** [comment]
This work has been completed
