### ISSUE TITLE
Micro Front Ends -- Consolidate All Shared Code into Shared Lib Directory

### ISSUE THREAD

**Issue by metal-messiah** [newrelic/newrelic-browser-agent#183]
#### Why

With some unknowns about the architecture still hanging, it will be important to make the process of moving files locations and their linking dependencies as smooth as possible.  The concern is removing the risk for circular dependencies as early as possible to avoid large re-architecting efforts later.  Putting ALL shared code into a universally accessible location will:
- Allow any module to reference the code without question as to where it belongs
- Remove circular dependencies of certain code living in one module but needed in another.

#### Tasks

- [x] Break all shared code into a common directory
- [x] Create and implement an architecture pattern here for use with other modules
    * New Unit tests could be housed here
- [x] Define a standardizable method of exporting dependancies and defaults for use with other modules
